---
- name: Test ping host all
  hosts: all
  #become: yes
  gather_facts: yes
  tasks:
  - name: Debug
    debug:
      msg: Hello
  - name: Download nodejs
    get_url:
      url: https://nodejs.org/dist/v14.17.6/node-v14.17.6-linux-x64.tar.xz
      dest: /opt/node.tar.xz
  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /opt/node.tar.xz
      dest: /opt/node
      remote_src: yes
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /opt/node
      state: directory
