---
- name: Test ping host all
  hosts: all
  #become: yes
  gather_facts: yes
  tasks:
  - name: Debug
    debug:
      msg: Hello
  - name: Download nodejs
    get_url:
      url: https://nodejs.org/dist/v14.17.6/node-v14.17.6-linux-x64.tar.xz
      dest: /opt/node.tar.xz
  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /opt/node
      state: directory
  - name: Extract foo.tgz into /var/lib/foo
    ansible.builtin.unarchive:
      src: /opt/node.tar.xz
      dest: /opt/node
      remote_src: yes
  - name: add to path
    lineinfile:
      dest: '/root/.profile'
      state: present
      line: 'export PATH=$PATH:/opt/node/node-v14.17.6-linux-x64/bin'
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote
    ansible.builtin.shell: . /root/.profile &&node --version
